### ISSUE TITLE
Vibration API

### ISSUE THREAD

**Issue by benhatsor** [web-platform-tests/interop#837] opened 2024-10-08 20:58 UTC
### Description

The entirety of the Vibration API, as defined in the W3C spec.

### Specification

https://www.w3.org/TR/vibration

### Additional Signals

Safari (WebKit) for iOS [does not support](https://caniuse.com/vibration) the [Vibration API](https://www.w3.org/TR/vibration). [Almost 80% of all browsers support it](https://caniuse.com/vibration). Chrome and Firefox have supported it since 2013 and Edge has supported it since 2020. The Vibration API is a W3C recommendation and Safari should support it.

The Vibration API is an important tool in creating native-like experiences and PWAs, [and](https://stackoverflow.com/questions/56926591/navigator-vibrate-break-the-code-on-ios-browsers) [many](https://stackoverflow.com/questions/71676847/does-ios-support-vibration) [developers](https://www.threads.net/@sdusteric/post/C5y2zJCytBk?hl=en) [have](https://www.reddit.com/r/webdev/comments/1d1vf7c/vibration_api_in_safari_ios/) [felt](https://gamedev.stackexchange.com/questions/143151/how-can-i-use-vibration-of-an-iphone-for-my-html-javascript-game) that the lack of this feature in Safari for so long is inhibiting them from implementing these cross-device experiences. Additionally, implementing this API in Safari can enable developers to add [additional haptic feedback for disabled users](https://stackoverflow.com/questions/56926591/navigator-vibrate-break-the-code-on-ios-browsers#comment108665170_56926591).

**Comment by lukewarlow** [comment] 2024-10-08 21:11
This appears to be a duplicate of https://github.com/web-platform-tests/interop/issues/718

**Comment by nairnandu** [comment] 2024-10-11 14:27
Closing this issue as a duplicate of #718

**Closed by nairnandu** 2024-10-11 14:27 UTC
Labels: focus-area-proposal
