### ISSUE TITLE
Consistent accessibility tree outputs

### ISSUE THREAD

**Issue by jelbourn** [web-platform-tests/interop#211] opened 2022-10-12 20:34 UTC
### Description

Browsers should investigate and work towards generating consistent accessibility tries from the same DOM + CSS.

### Rationale

All browsers produce subtly different accessibility trees for the same DOM + CSS. Some examples:
* [CSS `display` property impacts the a11y tree inconsistently](https://adrianroselli.com/2022/07/its-mid-2022-and-browsers-mostly-safari-still-break-accessibility-via-display-properties.html)
* https://www.powermapper.com/tests/screen-readers/aria/
* https://a11ysupport.io/
* For something more hands-on, on a macOS device, using VoiceOver to interact with this [W3C datepicker example](https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-datepicker.html) gives slightly different results between Chrome, Safari, and Firefox:
    > Chrome:
Date, dialog  pop up, Menu pop-up combobox
(date format: mm/dd/yyyy)
Choose date, dialog with 8 items, Entering October 2022 table. 12, October 2022, table, 7 columns, 7 rows

   > Safari:
   Date, dialog pop up, Menu pop-up combobox
   (date format: mm/dd/yyyy)
   Choose date, web dialog, with 8 items 12, Entering October 2022. 12, October 2022 table, 7 columns, 7 rows

   > Firefox:
   Date, combobox
   (date format: mm/dd/yyyy)
   Choose date, web dialog, with 8 items 12, Entering October 2022. 12, October 2022 table, 7 columns, 7 rows

While some differences are mostly innocuous ("dialog" vs "web dialog"), having any sort of standardization or interop testing would be a huge boon to all web developers trying to build accessible experiences. 

### Investigation Roadmap

See https://github.com/web-platform-tests/interop/issues/211#issuecomment-1295488697

(Description updated by @foolip Oct 31.)

**Comment by karlcow** [comment] 2022-10-13 07:02
do you mean the vocabulary should be standardized?

**Comment by jelbourn** [comment] 2022-10-13 17:22
> do you mean the vocabulary should be standardized?
Not exactly. I'm not an expert here, so it's possible that I'm missing something in my explanation. 

My understanding of the world today is that:
* Each browser produces an accessibility tree from a page's DOM + CSS
* Assistive technology, such as screen readers, operate from this accessibility tree
* There's no standard that describes _how_ browsers produce or structure this accessibility tree
* The easiest way to observe these differences is use the same screen reader on different browsers (Chrome, Safari, and Firefox do all expose some debug information about the a11y tree, but in such different formats that direct comparison isn't really possible) 

I see value in having some investigating these differences between browsers and potentially setting up tests that keep things consistent across platforms.

**Comment by chrishtr** [comment] 2022-10-13 18:11
> * Assistive technology, such as screen readers, operate from this accessibility tree

They use the tree in an indirect way (see below).

> * There's no standard that describes _how_ browsers produce or structure this accessibility tree

The "universal" accessibility tree is not in a spec, but the mapping to OS APIs is ([see here](https://www.w3.org/TR/core-aam-1.1/)).

> I see value in having some investigating these differences between browsers and potentially setting up tests that keep things consistent across platforms.

I agree. Unfortunately, there is not yet WPT infrastructure to test the OS mappings, or even to test the computed ARIA roles of elements. (And there is--by design--no web developer exposed API for any of these things.) I think we should fix this infrastructure problem in 2023 so that we can test interop for the accessibility tree in Interop 2024.

**Comment by karlcow** [comment] 2022-10-13 22:53
> The "universal" accessibility tree is not in a spec

Probably this should be discussed with W3C accessibility WGs.
Not sure Interop can do anything about it. In addition to what @chrishtr mentioned wrt the testing capabilities.

**Comment by foolip** [comment] 2022-10-24 13:57
@zcorpan I know that Bocoup has done a lot of work in this space. Do or colleagues have thoughts on the test infra side of this?

**Comment by chrishtr** [comment] 2022-10-25 23:20
I think we should treat this issue as a proposal for an Investigation area around improved accessibility testing in WPT. I'm gathering additional feedback now from Chrome a11y team experts and will make a more precise proposal soon.

**Comment by chrishtr** [comment] 2022-10-28 21:35
I've finished gathering support from within Chrome a11y experts. I'd like to update this proposal to the following:

Proposal: Accessibility Interop Testing
Type: [Investigation effort](https://github.com/web-platform-tests/rfcs/blob/master/rfcs/interop_2023.md#investigation-efforts)
Goal: enable interoperability testing of browser accessibility features in WPT. Interoperable means specified behaviors such as in [core accessibility mappings](https://www.w3.org/TR/core-aam-1.1/), [html accessibility mappings](https://www.w3.org/TR/html-aam-1.0/), and [aria computed roles](https://www.w3.org/TR/wai-aria-1.1/). None of these are currently testable via WPT. A secondary goal would be to investigate testing of interactive accessibility actions to and from OS APIs (and whether that is achievable without further specifications).

How: form an investigation group that works towards an accepted wpt.fyi [RFC](https://github.com/web-platform-tests/rfcs) for accessibility testing, and builds prototypes in browsers to verify this RFC is workable. It would receive a 100% score for all browsers if the RFC was accepted and at least one complete prototype implementation exists for at least one browser that runs some accessibility tests on wpt.fyi. This group will meet monthly through 2023 to work towards this goal.

----

Answers to the remaining questions from the RFC text for an investigation effort:

* Is this area a problem for web developers? Is this area a problem for users?

Developers very often experience lack of interop with a11y, which is always the result for any feature unless there is at least some interop testing in place. See also the links in the original comment for this issue. Users suffer as a result.

* How widely used is this feature?

A large fraction of the world's population have one need or another for a11y features (see [here](https://www.who.int/en/news-room/fact-sheets/detail/disability-and-health) for example). [This page](https://bthechange.com/how-many-people-with-disabilities-use-my-website-2e737caf55bf) indicates up to 20% of website visitors could be affected.

* Specification for this feature, if any. See links above under Goal.

**Comment by zcorpan** [comment] 2022-11-10 22:00
> @zcorpan I know that Bocoup has done a lot of work in this space. Do or colleagues have thoughts on the test infra side of this?

We've been working on [ARIA AT](https://aria-at.w3.org/) which is end-to-end screen reader tests, i.e. a test is some HTML+CSS+JS (currently the tests are based on [APG design pattern examples](https://www.w3.org/WAI/ARIA/apg/patterns/) but could be any tests) with a particular user interaction (pressing keys usually) and the assertions are done on the spoken output. This setup has no insight at all into what the browser's accessibility tree is like, or what is exposed to the OS accessibility API. But interop bugs somewhere in the "stack" can still be caught if they affect the spoken output. See https://github.com/w3c/aria-at-automation for work to support automation of these tests. 

Maybe [AOM](https://wicg.github.io/aom/explainer.html) or WebDriver accessibility primitives (https://github.com/w3c/webdriver/issues/1439 and https://github.com/w3c/webdriver/issues/1441) could help to test the browser's accessibility tree.

For testing OS APIs, I believe there are manual tests in wpt (e.g. [/accname/](https://wpt.live/accname/)), and IIRC there's tooling somewhere that automates those tests (not baked into wpt infra).

**Comment by cookiecrook** [comment] 2022-11-13 18:11
Testing the AccName spec (using computedLabel) may be a good first step:

https://github.com/w3c/accname/issues/174

**Comment by cookiecrook** [comment] 2022-12-02 02:26
Interop testing of _some_ TBD accessibility tree was one of the long-term original goals of AOM. One major complication is that WebKit based its internal tree off the RenderTree, compared to Gecko, which starts off the DOM tree. Chromium made a major implementation change a few years ago to more closely align with Gecko. All of the engine-internal accessibility trees mentioned here are distinct from the platform accessibility API trees.

IIRC where the AOM and ARIA groups landed in the shorter term was:

1. Focus on the automation properties that should be interoperable regardless of implementation. WebDriver computedLabel and computedRole are the first. Add more as needed.
2. Use those to test the more complicated part of accessibility interoperability, like the accessible name computation algorithm. (This testing recently became possible due to the WebDiver updates. Linked in prior comment.)
3. Add and test more accessibility automation properties as needed and agreed. For example, there is no standard way to verify that a checkbox is checked, regardless of whether it’s an HTML checkbox input or an ARIA checkbox/switch/etc.
4. If/When the interop testing gets around to computedParent/computedChild in the accessibility automation contexts, then we could have a comparison of where the browser internal trees differ and whether it’s necessary to start discussing the possibility of a standardized web accessibility tree, likely separate from the rendering engine internal accessibility tree, and the platform-specific accessibility trees.

As specified elsewhere, potential acceptance of ann AX tree investigation and other investigations for WPT would be conditional on a scoring change such that investigations should not penalize the score of any implementation.

**Comment by cookiecrook** [comment] 2022-12-02 02:31
Cc @spectranaut @alice @cyns @jnurthen

**Comment by foolip** [comment] 2023-02-01 17:58
Thank you for proposing consistent accessibility tree outputs for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Accessibility Testing investigation effort. You can follow the progress of this investigation on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

**Closed by foolip** 2023-02-01 17:58 UTC
Labels: accepted, investigation-effort-proposal

**Comment by cookiecrook** [comment] 2023-02-11 00:39
@foolip wrote:
> Thank you [@jelbourn] for proposing consistent accessibility tree outputs for inclusion in Interop 2023.
> We are pleased to let you know that this proposal was accepted 

For what it's worth, I'm all for an InterOp 2023 Accessibility Investigation, but "consistent accessibility tree outputs" is likely to be unachievable in 2023.

I'd love to help with the scoping of this investigation, and some of the effort.

**Comment by cookiecrook** [comment] 2023-02-14 22:29
Actually I see now @chrishtr proposed [a reduced scope](https://github.com/web-platform-tests/interop/issues/211#issuecomment-1295488697) (unrelated to tree consistency) that several of us at Apple think is much more achievable. 

> Goal: enable interoperability testing of browser accessibility features in WPT. Interoperable means specified behaviors such as in [core accessibility mappings](https://www.w3.org/TR/core-aam-1.1/), [html accessibility mappings](https://www.w3.org/TR/html-aam-1.0/), and [aria computed roles](https://www.w3.org/TR/wai-aria-1.1/). None of these are currently testable via WPT. A secondary goal would be to investigate testing of interactive accessibility actions to and from OS APIs (and whether that is achievable without further specifications).

I believe all or most HTML-AAM and role mapping tests are achievable using get_computed_role, while the AccName tests I'm starting on are mostly achievable using get_computed_label. There may be some minor differences related to pseudo-elements, UA Shadow DOM components, etc, but we can address these when we come to them.

I am not yet certain how we'd test the CoreAAM mappings as proposed, since those are all platform API specific, and would need platform-level verification that is currently outside the scope of WPT, if I understand correctly.

**Comment by cookiecrook** [comment] 2023-02-14 22:32
[SVG-AAM](https://w3c.github.io/svg-aam/) and [DPUB-AAM](https://w3c.github.io/dpub-aam/) may be similarly low hanging fruit that could be part of this investigation.

**Comment by cookiecrook** [comment] 2023-02-14 22:36
I'd like to move the /accname tests into /accessibility/manual, so that I can start on a set of automated tests covering AccName in /accessibility/accname

**Comment by gsnedders** [comment] 2023-02-14 23:22
> I am not yet certain how we'd test the CoreAAM mappings as proposed, since those are all platform API specific, and would need platform-level verification that is currently outside the scope of WPT, if I understand correctly. @zcorpan may have some ideas for how to incorporate those.

Further, as I understand it, it's unclear how many bugs testing Core-AAM would actually find, and it's by far the hardest thing to do from an infrastructure point of view. It seems like the investigation project should be much more heavily skewed towards the ARIA roles/labels the browser believes things have.

**Comment by zcorpan** [comment] 2023-02-18 21:59
We'd need some way of interfacing with the platform accessibility API to test core-aam. Or maybe the browser "knows" what the mapping is, and can expose it to WebDriver?

Maybe testing core-aam is more of the realm of ARIA-AT than wpt, although ARIA-AT doesn't currently directly test the platform accessibility API either. cc @jugglinmike
