### ISSUE TITLE
WebVTT Rendering

### ISSUE THREAD

**Issue by danae404** [web-platform-tests/interop#874] opened 2024-10-09 21:08 UTC
### Description

Inconsistent rendering of WebVTT across web browsers makes the format unattractive to web developers, who instead choose to use parse and render subtitles in javascript, which is incompatible with macOS and iOS system accessibility settings and fullscreen modes. A WebVTT Rendering focus area is important for increasing its usage on the web.

### Specification

https://w3c.github.io/webvtt/

### Additional Signals

This proposal [was discussed](https://www.w3.org/2024/09/27-tt-minutes.html#t09) at the Timed Text WG at TPAC this year, and the group unanimously supported its inclusion in Interop 2025. 

There is an existing [test suite](https://github.com/web-platform-tests/wpt/tree/master/webvtt/rendering/cues-with-video/processing-model) for WebVTT Rendering. [Low scores](https://wpt.fyi/results/webvtt/rendering?label=experimental&label=master&aligned) demonstrate a severe lack of interoperability between browsers, with no browser passing more than 30% of the tests.

**Comment by danae404** [comment] 2024-10-09 21:10
It looks like a related proposal was filed as issue #860

**Comment by jgraham** [comment] 2024-10-10 08:30
I'm going to close this as a duplicate of the earlier issue because they appear to have identical scopes. Please add any extra context you want in that issue.

**Closed by jgraham** 2024-10-10 08:30 UTC
Labels: focus-area-proposal
