### ISSUE TITLE
Overflow Anchor

### ISSUE THREAD

**Issue by Westbrook** [web-platform-tests/interop#793] opened 2024-10-07 13:53 UTC
### Description

Allow scroll anchoring to be managed by the developer to include custom contexts like, pinning the scroll to the end of the dynamic content.

```css
.scroller {
    overflow: auto;
    
    > * {
        overflow-anchor: none;
    }

    > #anchor {
        overflow-anchor: auto;
    }
}
```

Learn more about how you can Pin Scrolling content to the end with this API, [here](https://css-tricks.com/books/greatest-css-tricks/pin-scrolling-to-bottom/).

### Specification

https://drafts.csswg.org/css-scroll-anchoring/#exclusion-api

### Additional Signals

[WPTs](https://wpt.fyi/results/css/css-scroll-anchoring?label=master&product=edge%5Bexperimental%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&product=chrome%5Bexperimental%5D&product=chrome%5Bbeta%5D&q=overflow%20anchor)

**Comment by Westbrook** [comment] 2024-10-09 13:17
https://github.com/web-platform-tests/interop/issues/826

**Comment by nt1m** [comment] 2024-10-25 21:56
Closing as duplicate of #826 since it has more info.

**Closed by nt1m** 2024-10-25 21:56 UTC
Labels: focus-area-proposal
