### ISSUE TITLE
Scroll snap

### ISSUE THREAD

**Issue by flackr** [web-platform-tests/interop#14] opened 2021-11-10 21:29 UTC
**Description**
css-scroll-snap allows creating popular UX paradigms for paged or itemized content, and is essential for taking advantage of the browser's accelerated scrolling mechanisms and not having to reimplement fling physics to make these experiences as smooth and seamless as possible.

**Specification**
https://drafts.csswg.org/css-scroll-snap/

**Tests**
Links to web-platform-tests (on https://wpt.fyi) for the feature:
*  [Existing tests](https://wpt.fyi/results/css/css-scroll-snap?label=master&label=experimental&aligned&q=%20snap-inline-block.html%20or%20snap-after-relayout%20or%20scroll-snap-type-on-root-element.html%20or%20scroll-snap-root-003.html%20or%20overflowing-snap-areas.html%20or%20nested-scrollintoview-snaps.html) which demonstrate RTL issues or significant feature deltas
* Tests to be written
  * Arrow keys should smooth scroll to next snap target
  * Mouse wheel click should immediately scroll to next target
  * When snap area is larger than viewport it should snap to nearest edge (currently jumps to initial snap position), see [related csswg issue](https://github.com/w3c/csswg-drafts/issues/6863).

**Rationale**
Major UX experiences (e.g. carousels, paginated content, etc) are enabled by this feature but lack of polish prevents widespread use. While we tackled and greatly improved the interop in 2021, there are still a few significant gaps. The 2021 scroll survey confirms [carousels are important but not yet easy to manage](https://web.dev/2021-scroll-survey-report/#carousels).

**Comment by mrobinson** [comment] 2021-11-12 14:08
The existing tests here might be a bit misleading, because a lot of issues are fixed in upstream WebKit already. You can see the delta is a bit smaller if you add the experimental version of WebKitGTK to the list of browsers.

**Comment by flackr** [comment] 2021-11-25 21:32
@kevers-google is adding the extra few tests.

**Comment by foolip** [comment] 2022-01-10 14:57
A proposed list of tests has been labeled with [`interop-2022-scrolling`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-scrolling). It would be great if someone from each browser engine team can look over this list and comment if there are any issues.

**Comment by flackr** [comment] 2022-01-18 18:57
Looks like we're missing css/css-scroll-snap/input/mouse-wheel.html which is one of the newly added tests. Note that in adding these tests we discovered some issues with the test driver event injection, see [crbug.com/1285411](https://crbug.com/1285411)

**Comment by foolip** [comment] 2022-01-20 15:15
A bunch of scrolling tests came up in my analysis in https://github.com/web-platform-tests/interop-2022/issues/48. It spans this issue and https://github.com/web-platform-tests/interop-2022/issues/21, but I'll past the whole comment since the root cause seems shared across the two in one case:

> There are 3 tests that use `new test_driver.Actions().scroll(...)` and either ERROR or TIMEOUT in Firefox/Safari:
> 
> * [/css/css-overscroll-behavior/overscroll-behavior.html](https://wpt.fyi/results/css/css-overscroll-behavior/overscroll-behavior.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in both Firefox and Safari.
> * [/css/css-scroll-snap/input/snap-area-overflow-boundary.html](https://wpt.fyi/results/css/css-scroll-snap/input/snap-area-overflow-boundary.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in Firefox and TIMEOUT in Safari.
> * [/css/css-scroll-snap/snap-at-user-scroll-end.html](https://wpt.fyi/results/css/css-scroll-snap/snap-at-user-scroll-end.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in both Firefox and Safari.
> 
> https://bugzil.la/1746601 is the Gecko bug about this testdriver API. The harness errors can probably be fixed with the proper `t.step_func` wrapping or similar.
> 
> [/css/css-scroll-snap/input/keyboard.html](https://wpt.fyi/results/css/css-scroll-snap/input/keyboard.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Firefox and Safari, but the first test runs and fails in Firefox. I don't think this is due to a missing testdriver.js API, but it needs investigation.
> 
> [/css/cssom-view/scroll-behavior-smooth.html](https://wpt.fyi/results/css/cssom-view/scroll-behavior-smooth.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in Chrome and TIMEOUT in Safari. Needs investigation.

**Comment by flackr** [comment] 2022-03-03 20:53
@kevers-google, could you look into some of these failures?

**Comment by kevers-google** [comment] 2022-03-03 20:56
Will do

**Comment by kevers-google** [comment] 2022-03-14 22:13
Started looking at the tests involving new test_driver.Actions().scroll(...) .  Wheel scrolls do not appear to be supported in test_driver on Firefox or Safari.  

Based on https://web-platform-tests.org/writing-tests/testdriver.html#test_driver.action_sequence, Actions.send() should reject the
promise if any of the actions fail, so the following example should pass or fail based on whether a wheel scroll was successfully dispatched:

promise_test(t => {
  return new test_driver.Actions().scroll(200, 500, 0, -200).send();
}, 'Simple test');

This minified test is triggering an ERROR instead of a Fail on Firefox (don't have a Mac for testing on Safari).  Thus, I don't believe that a test.step will address the harness error.  Having said that, overscroll-behavior.html is mixing test.step with promise chains and would likely benefit from being changed to a series of promise tests: one for each of the 4 conditions being tested.  

Will review the other tests shortly.

**Comment by karlcow** [comment] 2022-03-14 22:51
> Started looking at the tests involving new `test_driver.Actions().scroll(...)` . Wheel scrolls do not appear to be supported in test_driver on **Firefox** or Safari.

For Firefox, there's a in-progress patch from @jgraham 
https://phabricator.services.mozilla.com/D139123

**Comment by kevers-google** [comment] 2022-03-15 13:40
Keyboard.html is Timing out if not seeing the expected scroll in response to a keypress.  Since the first test works, it would suggest that Firefox supports test_driver.send_keys().  If  'arrowup' in the second test is replaced with 'pageup' then we reach the desired snap point.  If waitForScrollEnd(target_position) is replaced with waitForAnimationEnd(get_position_callback) then we see that the page doesn't switch snap points in response to arrow up.  Though waitForAnimationEnd would change a Timeout to a Fail, it was the disadvantage of being potentially flaky since it depends on waiting for nothing to happen for a number of animation frames to infer that scrolling has stopped. Ultimately waitForScrollEnd results in faster test execution when everything is scrolling properly since we don't have the extra rAF wait time.

**Comment by mrobinson** [comment] 2022-03-15 13:53
> Keyboard.html is Timing out if not seeing the expected scroll in response to a keypress. Since the first test works, it would suggest that Firefox supports test_driver.send_keys(). If 'arrowup' in the second test is replaced with 'pageup' then we reach the desired snap point. 

There are a couple more issues with this particular test as well:
- It assumes that a non-focusable element can receive keys, but I don't think this follows the WebDriver specification. From https://www.w3.org/TR/webdriver/#element-send-keys:
  > The [Element Send Keys](https://www.w3.org/TR/webdriver/#dfn-element-send-keys) [command](https://www.w3.org/TR/webdriver/#dfn-commands) [scrolls into view](https://www.w3.org/TR/webdriver/#dfn-scrolls-into-view) the form control [element](https://www.w3.org/TR/webdriver/#dfn-elements) and then sends the provided keys to the [element](https://www.w3.org/TR/webdriver/#dfn-elements). 

  I have a fix for this here: https://github.com/web-platform-tests/wpt/pull/33151
- It assumes that scrolls will use smooth scrolling. This isn't currently the case with WebKit on Mac, so this test fails even with the fix above.

**Comment by foolip** [comment] 2022-03-18 18:49
Thanks for digging into the failures, @kevers-google and @mrobinson! For the tests that error instead of fail, does someone have the time to try fixing those to properly fail instead?

**Closed** 2022-08-18 09:18 UTC
Labels: proposal, accepted
