### ISSUE TITLE
Accessibility (computed role + computed label)

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/interop#526] opened 2023-10-04 14:13 UTC
### Description

Fix interop bugs in the browser’s accessibility tree for the parts that are now testable in wpt as a result of the [interop-2023 accessibility testing investigation area](https://github.com/web-platform-tests/interop-2023-accessibility-testing/), for the benefit of users who need assistive technology and for web developers wishing to design accessible user interfaces on the web.

### Specification

https://w3c.github.io/aria/ https://w3c.github.io/accname/ https://w3c.github.io/html-aam/

### Tests

https://wpt.fyi/results/?label=master&label=experimental&aligned&q=label%3Aaccessibility

More specifically, the “priority 1” tests in https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/3 (some tests are open PRs, some are not yet created but should be soon). Exclude “priority 2” (graphics role, SVG, DPUB).

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

### Polls & Surveys

in [preliminary results from State of HTML 2023](https://github.com/web-platform-tests/interop/issues/550), ARIA was a common response to the question "Which existing HTML features or browser APIs are you unable to use because of browser differences or lack of support?"

Also see `accessibility_pain_points` responses in the same survey: https://coda.io/d/State-of-HTML-Preliminary-Results_d7UVQ_fZW0V/Other-Core-Pain-Points_suDnF#Other-Core-Pain-Points_tuN-h/r4723

> Inconsistent handling of elements/components between screen readers & browsers

> As a FOSS developer, I can only test for browser/OS/AT combinations I personally own and that doesn't give me enough confidence

> Most of the problems are UA problems - the UAs need to be quicker to fix bugs, so that developers who implement the specs can be confident they aren't doing the wrong thing

> Browser support

> Segmented support between browsers and OSes, have hit many cases I can support in 2 browsers but not a third. Safari and Firefox are the usual culprit.

> Inconsistency between AT and browsers on how information is exposed.

> Differences between browsers and tools (e.g. NVDA vs VoiceOver)

> Difference between browsers, OS and screen readers

> browser/AT interop

> Different browsers expose different information to different assistive technology tools in different ways. Testing accessibility is a huge burden due to the discrepancies between the AT

### Accessibility Impact

Positive; this is explicitly designed to improve interop of some of the most important browser accessibility features.

**Comment by foolip** [comment] 2023-10-05 14:06
For survey data and web developer demand, in [preliminary results from State of HTML 2023](https://github.com/web-platform-tests/interop/issues/550), ARIA was a common response to the question "Which existing HTML features or browser APIs are you unable to use because of browser differences or lack of support?"

**Comment by dtsengchromium** [comment] 2023-10-10 15:52
I think there's issues with the tests themselves and the way they fetch data from Chrome. One issue I've written up follows.

WPT calls into webdriverio
https://github.com/webdriverio/webdriverio
in
webdriverio/packages/devtools/src/commands/getElementComputedRole.ts
 `accessibility.snapshot`

which is Puppeteer
https://github.com/puppeteer/puppeteer
puppeteer/packages/puppeteer-core/src/cdp/Accessibility.ts
which sends the CDP command
Accessibility.getFullAXTree
with the `interesting` option defaulted to true.

In Chrome,
getFullAXTree
InspectorAccessibilityAgent::getFullAXTree
gets called and returns the tree back over CDP.

Back in Puppeteer,
puppeteer/packages/puppeteer-core/src/cdp/Accessibility.ts
`Accessibility.snapshot`

the tree is filtered for "interesting nodes". This amounts to calling into its own wrapper `AXNode` ts object `isInteresting` method.

That method has some definition of interesting which includes only some elements e.g. controls, leaves (with text), etc. That explains a lot of failures within the dashboard pertaining to roles.

I'm therefore not sure we can use the test results here until the underlying tooling is reliable/corrected. Specifically here, the simplest thing is for WPT to pass interesting to false
https://pptr.dev/api/puppeteer.accessibility.snapshot

**Comment by cookiecrook** [comment] 2023-10-10 18:06
@jcsteh The [full AX tree dump investigation](https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/51) is not part of this proposal, so unless I'm misunderstanding, your comments would NOT block this Interop 2024 Focus Area proposal… Is that correct?

**Comment by cookiecrook** [comment] 2023-10-10 18:10
Though I could see [ARIA Reflection (Gecko bug 1858211)](https://bugzilla.mozilla.org/show_bug.cgi?id=1858211) being a problem for Gecko if there are objections to the test expectations or spec. If so, we could exclude that test from the Focus Area too.

**Comment by jcsteh** [comment] 2023-10-11 00:36
> @jcsteh The [full AX tree dump investigation](https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/51) is not part of this proposal, so unless I'm misunderstanding, your comments would NOT block this Interop 2024 Focus Area proposal… Is that correct?

I don't see any comments from me on this particular issue, so I assume you're referring to https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/51#issuecomment-1613838467? So no, those comments don't block this because it's out of scope.

You're correct that ARIA element reflection is a problem for us with regard to this focus area. This should be discussed somewhere else, but as I understand it, one of the primary use cases of that entire spec is to support references across shadow DOM, yet it doesn't actually achieve that goal because of the encapsulation problem.

There are a few other tests I think we should consider excluding from this as well for various reasons, but I'll provide more details on that once I've finished my triage.

**Comment by jcsteh** [comment] 2023-10-11 04:30
There seem to be some tests where we don't have a clear path forward and no engine is passing. For example, [html-aam/fragile/area-role.html](https://wpt.fyi/results/html-aam/fragile/area-role.html?label=master&label=experimental&aligned&q=firefox%3A%21pass%20firefox%3A%21ok%20label%3Aaccessibility) and el-thead/el-tfoot/el-tbody in [html-aam/table-roles.html](https://wpt.fyi/results/html-aam/table-roles.html?label=master&label=experimental&aligned&q=firefox%3A%21pass%20and%20label%3Aaccessibility). We'll either need to exclude these or collectively determine a path forward in order to get them passing.

**Comment by dtsengchromium** [comment] 2023-10-11 14:06
@cookiecrook

My comment above was referring to the way in which trees were fetched for the tests and went into detail on the manner WPT does it. Happy to have that corrected if I missed something. The takeaway is that many of the results don't mean anything at the moment.

Separate questions are whether webdriver is the right component to base these tests off of and if so, whether its worth making contributions there. For Chrome, webdriver leverages puppeteer. Who wants to make contributions to those projects to get things working? IIRC, those projects primarily concern themselves with test automation.

 Also, note that puppeteer is fetching Chrome's internal Blink side a11y tree. This is probably not the right tree to test against. For example, the role literals are internal programmatic identifiers and not stable. The name computation is incomplete since we do different things for each platform a11y api (grant it, in the minority of cases).

 The platform trees are the only stable representation which we really service (e.g. NSAccessibility, IAccessible2, etc). These questions and others worth a discussion at the next meeting for a11y interop.

**Comment by boazsender** [comment] 2023-10-12 16:49
I agree with @cookiecrook that https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/51 is not part of this proposal as it's written. This proposal is about closing interop gaps from WPTs that don't use the axe tree.

@dtsengchromium what you're saying makes sense that makes sense, we reached the same conclusion at Bocoup when we tried to use the available accessibility tree dump through cdp with the intention of testing core-aam and realized we couldn't for the reason you've mentioned here. I think we should continue this conversation on https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/51 and discuss the best path forward for exposing the platform trees for testing aam.

I also started an issue here about continuing the 2023 accessibility investigation area into 2024, which is a place where I think we could continue this work if we don't advance it further this year: https://github.com/web-platform-tests/interop/issues/459

So the tree dumping conversation would be part of the 2024 investigation area carry over, whereas this issue is a new focus area for closing interop bugs from tests based on things like getcomputedrole. I know it's a lot of interop jargon, so apologies for the category nitpicking. Where these things fall ends up being important for the wpt interop prioritization process. That's the only reason I'm pushing on this detail.

**Comment by zcorpan** [comment] 2023-10-12 20:19
I think there's some misunderstanding here; as noted in https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/65#issuecomment-1757757177 , @dtsengchromium did not comment about tests using tree dump (which don't yet exist?) but about tests using get computed role (which is implemented using `getFullAXTree` for Chrome).

**Comment by boazsender** [comment] 2023-10-12 20:37
Ah I understand now, thanks for clarifying @zcorpan.

@dtsengchromium what do you think would the best path forward for changing the underlying tooling?

**Comment by cookiecrook** [comment] 2023-10-13 01:25
Yes, thanks for clarifying… FWIW, Chromium is already passing ~92% of [the tests proposed for next year](https://wpt.fyi/results/?label=master&label=experimental&aligned&q=label%3Aaccessibility), but I can see the [HTML-AAM: el-code](https://wpt.fyi/results/html-aam/roles.html?label=master&label=experimental&aligned&q=label%3Aaccessibility) test is failing as @dtsengchromium describes.

**Comment by cookiecrook** [comment] 2023-10-13 01:30
@jcsteh wrote:
> I don't see any comments from me on this particular issue, 

Yes, sorry. That was a GitHub autocomplete that I mistakenly confirmed. Apologies as I meant to reply to @dtsengchromium

**Comment by jensimmons** [comment] 2023-11-01 21:08
We should figure out how to define the scope of the tests chosen for Interop 2024, and then set the scope. Not keep letting it grow over the course of the year.

**Comment by jugglinmike** [comment] 2023-11-02 01:23
@dtsengchromium Thanks for that analysis! I wanted to understand the extent of the dependency on webdriverio, and I figured that I'd be able to find it in WPT since most of the "priority 1" tests which @zcorpan references have been completed. I searched WPT for references to webdriverio, but nothing came up:

    $ git log -n1 --format='%h %ci %s'
    b2528beea2 2023-11-01 11:05:04 -0700 [css-tables] Make `col-change-span-bg-invalidation*.html` tests fuzzy (#42897)
    $ grep -ir webdriverio . | wc -l
    0
    $ find . -iname '*webdriverio*' | wc -l
    0

I thought maybe we're talking about the Chromium project's integration with WPT, but I couldn't find any references in Chromium's source tree, either:

    $ git log -n1 --format='%h %ci %s'
    a87e318028 2023-11-02 00:55:19 +0000 Cleanup "inverse-fieldtrial" trybots.
    $ grep -ir webdriverio . | wc -l
    0
    $ find . -iname '*webdriverio*' | wc -l
    0

Would you mind pointing me in the right direction?

**Comment by dtsengchromium** [comment] 2023-11-02 03:24
@jugglinmike I'm not too familiar with the WPT repo and how it's set up and it's been a couple of weeks. What you're looking for in WPT is the point at which it calls get computed role (I don't recall the exact method name). I traced down a couple of layers in WPT from the test html file to a common test ts file which appeared to lead to web driver.

**Comment by jugglinmike** [comment] 2023-11-07 19:30
After tracing the flow of control, I've found a couple aspects that differ from what @dtsengchromium [reported](https://github.com/web-platform-tests/interop/issues/526#issuecomment-1755733993):

1. The tests appear to be instructing WPT's test runner to send WebDriver commands to Chromedriver (that is, neither `webdriverio` nor Puppeteer appear to be involved)
2. It seems as though the CDP command named `Accessibility.getPartialAXTree` is in use (not `Accessibility.getFullAXTree`)

These discrepencies are important because they impact how we'll fix the problem (and plan for the fix). I'll share the complete trace in the hopes that someone can verify my research or more precisely dispute it. (It's even more likely than normal that I've made a mistake because this infrastructure has been built with extension in mind.)

- [the tests call `AriaUtils.verifyLabelsBySelector`](https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt+verifyLabelsBySelector&type=code)
- [`AriaUtils.verifyLabelsBySelector` calls `test_driver.get_computed_label`](https://github.com/web-platform-tests/wpt/blob/e498a35b8f9fa3c98cc0d3bb287d52c008faff90/wai-aria/scripts/aria-utils.js#L140)
- [testdriver.js delegates to `test_driver_internal.get_computed_label`](https://github.com/web-platform-tests/wpt/blob/e498a35b8f9fa3c98cc0d3bb287d52c008faff90/resources/testdriver.js#L236)
- in WPT's test environment[^1], [wptrunner injects `testdriver-extra.js`](https://github.com/web-platform-tests/wpt/blob/e498a35b8f9fa3c98cc0d3bb287d52c008faff90/tools/wptrunner/wptrunner/environment.py#L313-L331)
- [`test_driver_internal.get_computed_label` calls `create_action`](https://github.com/web-platform-tests/wpt/blob/e498a35b8f9fa3c98cc0d3bb287d52c008faff90/tools/wptrunner/wptrunner/testdriver-extra.js#L186)
- [`create_action` pushes to `__wptrunner_message_queue`](https://github.com/web-platform-tests/wpt/blob/e498a35b8f9fa3c98cc0d3bb287d52c008faff90/tools/wptrunner/wptrunner/testdriver-extra.js#L134)
- [`testharnessreport.js` invokes `__wptrunner_testdriver_callback` with the message](https://github.com/web-platform-tests/wpt/blob/e498a35b8f9fa3c98cc0d3bb287d52c008faff90/tools/wptrunner/wptrunner/testharnessreport.js#L67-L69)
- [`testharness_webdriver_resume.js` defines `__wptrunner_testdriver_callback` as the argument...](https://github.com/web-platform-tests/wpt/blob/e498a35b8f9fa3c98cc0d3bb287d52c008faff90/tools/wptrunner/wptrunner/executors/testharness_webdriver_resume.js)
- [...to the "async script" command of WebDriver in `WebDriverTestharnessExecutor.do_testharness`](https://github.com/web-platform-tests/wpt/blob/f30784e70ca6582f3d705ce309082c4271375116/tools/wptrunner/wptrunner/executors/executorwebdriver.py#L544-L545)
- [passing the result to `WebDriverCallbackHandler.__call__`](https://github.com/web-platform-tests/wpt/blob/f30784e70ca6582f3d705ce309082c4271375116/tools/wptrunner/wptrunner/executors/executorwebdriver.py#L612)
- [which delegates to `GetComputedLabelAction`](https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/executors/base.py#L738-L742)
- [`GetComputedLabelAction` calls `WebDriverAccessibilityProtocolPart.get_computed_label`](https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/executors/actions.py#L52)
- [`WebDriverAccessibilityProtocolPart.get_computed_label` invokes `WebElement.get_computed_label`](https://github.com/web-platform-tests/wpt/blob/f30784e70ca6582f3d705ce309082c4271375116/tools/wptrunner/wptrunner/executors/executorwebdriver.py#L212)
- [`WebElement.get_computed_label` sends the `computedlabel` WebDriver command](https://github.com/web-platform-tests/wpt/blob/f30784e70ca6582f3d705ce309082c4271375116/tools/webdriver/webdriver/client.py#L874-L876)
- [ChromeDriver calls `ExecuteGetComputedLabel`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/chromedriver/server/http_handler.cc;l=422-425;drc=90d873d975ed035b8c9795b534e4fe4e0fa4e32c)
- [`ExecuteGetComputedLabel` calls `GetAXNodeByElementId`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/chromedriver/element_commands.cc;l=830;drc=bf13b228ca470e5c1ba5d9c94229084dcc1b9fe2)
- [`GetAXNodeByElementId` sends the CDP command `Accessibility.getPartialAXTree`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/chromedriver/element_util.cc;l=921-922;drc=7fa0c25da15ae39bbd2fd720832ec4df4fee705a)

[^1]: [The Chromium project inserts a custom definition of `test_driver_internal`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/resources/testdriver-vendor.js;drc=143ff0058d0bb1f6999bb62b8d18dad6986f3299), but I haven't analyzed that path because [we're considering the test results published on wpt.fyi](https://github.com/web-platform-tests/interop/issues/526#issuecomment-1755733993).

**Comment by cookiecrook** [comment] 2023-11-07 20:19
Addressing the above subthread in this tracking issue. https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/65

**Comment by cookiecrook** [comment] 2023-11-07 21:44
The fragile tests should be excepted from the Interop Focus Area proposal if https://github.com/web-platform-tests/wpt/issues/39617 is not resolved.

- https://wpt.fyi/results/html-aam/fragile
- I may have another outstanding PR for fragile tests in `wai-aria` or `accname` too

**Comment by gsnedders** [comment] 2023-11-29 19:15
> https://wpt.fyi/results/?label=master&label=experimental&aligned&q=label%3Aaccessibility
> 
> More specifically, the “priority 1” tests in [web-platform-tests/interop-accessibility#3](https://github.com/web-platform-tests/interop-accessibility/issues/3) (some tests are open PRs, some are not yet created but should be soon). Exclude “priority 2” (graphics role, SVG, DPUB).

This leaves, what? https://wpt.fyi/results/?label=master&label=experimental&aligned&q=label%3Aaccessibility%20and%20not%20path%3A%2Fsvg-aam%20and%20not%20path%3A%2Fdpub-aam%20%20and%20not%20path%3A%2Fgraphics-aria%20and%20not%20is%3Atentative maybe?

**Comment by cookiecrook** [comment] 2023-11-29 23:14
Perhaps also `not path:/html-aam/fragile` (I can rename that dir tentative if that's better)... I think it's unclear what the role should return of never-rendered elements like image `map > area`

https://wpt.fyi/results/?label=master&label=experimental&aligned&q=label%3Aaccessibility%20and%20not%20path%3A%2Fsvg-aam%20and%20not%20path%3A%2Fdpub-aam%20%20and%20not%20path%3A%2Fgraphics-aria%20and%20not%20is%3Atentative%20and%20not%20path%3A%2Fhtml-aam%2Ffragile%20

**Comment by cookiecrook** [comment] 2023-12-05 20:26
Accessibility WPT meeting: Group opinion is that the Chromium implementation issue is not a blocker for this Focus Area. The bug in ChromeDriver (if that's where the bug is) can be fixed as part of the effort to improve the Focus Area score.

**Comment by cookiecrook** [comment] 2023-12-06 15:15
The [SVG-specific tests](https://wpt.fyi/results/svg-aam?label=master&label=experimental&aligned&q=label%3Aaccessibility) were Priority 2 for the investigation and therefore excluded from this Focus Area tests, but of the 26 SVG tests finished for the investigation…

- WebKit passes 25 of 26.
- Chromium passes 25 of 26.
- Gecko passes 17 of 26.

So we could leave it up to Mozilla to determine whether to include those 26.

**Comment by jcsteh** [comment] 2023-12-11 04:18
I think it's reasonable to include these. I do have an open question about one of them (also failed by Chromium) in https://github.com/w3c/svg-aam/issues/32#issuecomment-1849286821.

**Comment by zcorpan** [comment] 2023-12-11 15:09
@foolip is including the SVG tests ok for Chromium? ([see above](https://github.com/web-platform-tests/interop/issues/526#issuecomment-1843090941))

**Comment by jensimmons** [comment] 2023-12-21 18:02
Tests of `display:contents` for consideration to include: https://github.com/web-platform-tests/wpt/pull/43740

**Comment by dtsengchromium** [comment] 2024-01-06 01:26
@foolip


Thanks for the analysis!

I think I wasn't quite following the specific CDP calling component correctly. Whether it was web driver/puppeteer or Chrome driver, it's good to see the specific CDP protocol api being used.

It's possible
getPartialAccessibilityTree
https://chromedevtools.github.io/devtools-protocol/tot/Accessibility/
is only returning pruned results, the ancestors/siblings are not being included, etc.

The api itself is also marked as experimental, so I'm guessing it was never meant to be consumed publically beyond internal callers. In other words, it was never seriously tested.

This entire path has no relation to what we serve up to ATs, so that's why I'd still consider it infrastructure bugs rather than a real test failure.

**Comment by cookiecrook** [comment] 2024-01-06 07:33
@dtsengchromium No need to post that update here because it's not relevant to the Accessibility Interop Focus Area this issue is tracking. 

There's another issue tracking the ChromeDriver bug in `ExecuteGetComputedLabel`. Please update that one:
- https://github.com/web-platform-tests/interop-accessibility/issues/65

**Comment by cookiecrook** [comment] 2024-01-12 01:46
Minor adjustment to the issue title because not all the label stuff (img alt or html:label for example) that we are testing is defined in the AccName spec.

**Comment by cookiecrook** [comment] 2024-01-12 01:49
As an aside, all the `display: contents;` accessibility tests from #568 are also only able to confirm testing via computedrole and computedlabel, so those tests could be roled under this one if desired, as opposed to a separate Focus Area.

**Comment by dandclark** [comment] 2024-02-01 18:00
This proposal has been accepted as part of Interop 2024!  On behalf of the entire Interop team, thank you for proposing it.  You’ll be able to track progress on this topic throughout the year via the [Interop 2024 dashboard](https://wpt.fyi/interop-2024).

**Closed by dandclark** 2024-02-01 18:00 UTC
Labels: focus-area-proposal

**Comment by cookiecrook** [comment] 2024-03-06 01:16
FYI some subtests in the tracked Focus Area files will be removed due to this bug:
- https://github.com/web-platform-tests/interop-accessibility/issues/109

**Comment by zcorpan** [comment] 2024-03-06 08:15
@cookiecrook can you [file a test change proposal](https://github.com/web-platform-tests/interop/issues/new/choose)?

**Comment by cookiecrook** [comment] 2024-04-22 23:29
- https://github.com/web-platform-tests/interop/issues/654
