### ISSUE TITLE
Support for background image-set()

### ISSUE THREAD

**Issue by fellyph** [web-platform-tests/interop#156] opened 2022-09-26 14:30 UTC
### Description

image-set() property, is only supported by 74% of the browsers, this feature can be a good performance improvement for the web, because actually background images are heavily used by CMS and page builders and some case the images included only accept one size. There are other solutions to solve it but image-set could simplify this implementation. 

### Rationale

Some CMS, such as WordPress, has components to display a hero image, and some scenarios when is included a parallax effect or some other reason. the image is included via background image, and by most of the browser only accepts one image size for all screens, the ideal scenario is to load a size for each size of screen and css function image-set() can be a alternative for it.

### Specification

https://drafts.csswg.org/css-images-4/#funcdef-image-set

**Comment by atjn** [comment] 2022-09-27 13:21
IMO `image-set()` is a great candidate for web compat 2023 because of the [very fragmented support for its sub-features](https://caniuse.com/css-image-set). If you want to use it in production right now, you have to write and test three different versions, one for each major browser engine. It would be very helpful if this could be simplified.

**Comment by atjn** [comment] 2022-09-27 13:39
Another compat issue that could be adressed, is compatibility between the `<picture>` element and ` image-set()`.

`<picture>` supports the `w`/`h` keys to denote resolution. This is more universally useful than using the `x` key. Unfortunately, `w`/`h` has not yet been added to the `image-set` spec. This means that image minification pipelines have to treat images differently, depending on whether they will be imported with `html` or `css`. It would greatly simplify these tools if it was possible to use a single pipeline for all images.

The spec already mentions that this should be added in `ISSUE 2`.

**Comment by foolip** [comment] 2022-09-27 14:06
I've only skimmed the issues, but is this a duplicate of https://github.com/web-platform-tests/interop/issues/144? If so, could  you (@jsnkuhn and @fellyph) work together on a single proposal?

**Comment by atjn** [comment] 2022-09-27 14:16
I'd say you can close this as a duplicate of #144, since that one is more detailed and covers more use cases. Too bad I added my comments to the duplicate 😅

**Comment by fellyph** [comment] 2022-09-27 17:21
It is fine, I can also add comments on the issue #144

**Comment by foolip** [comment] 2022-09-27 17:47
Great, thanks for understanding!

**Closed** 2022-09-27 17:46 UTC
Labels: focus-area-proposal

**Comment by fellyph** [comment] 2022-09-27 17:59
@foolip can I close this issue?
