### ISSUE TITLE
Pointer events

### ISSUE THREAD

**Issue by flackr** [web-platform-tests/interop#15] opened 2021-11-10 22:59 UTC
**Description**
The pointerevents spec provides a unified input model for handling pointing devices regardless of their type (e.g. mouse, touch, stylus) and contains many new capabilities to these events such as predicted points and pointer capture.

**Specification**
https://w3c.github.io/pointerevents/

**Tests**
Links to web-platform-tests (on https://wpt.fyi) for the feature:
https://wpt.fyi/results/pointerevents?label=master&label=experimental&aligned

**Rationale**
The pointerevents spec is where new input features are arriving and developers using pointerevents instead of mouse or touch event listeners improves usability across input modalities. Additionally, using touch-action and passive event listeners improves scrolling performance. However, differences in behavior can lead to adoption or usability issues.

**Comment by jgraham** [comment] 2021-11-11 11:32
This is an feature where we see a relatively large number of developer-filed bug reports, indicating that it's something that people run into when creating sites (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1529904, https://bugzilla.mozilla.org/show_bug.cgi?id=1675846, https://bugzilla.mozilla.org/show_bug.cgi?id=1695574) so I agree that this makes sense as a focus area.

**Comment by gsnedders** [comment] 2021-11-11 17:25
Note that Safari doesn't support touch events on macOS (the only platform on wpt.fyi), because macOS doesn't support touch input, as such I think we'd be opposed to including the touch action tests in this bracket. (Not making any statement about the inclusion of the rest of pointer events, just noting that there is that limitation.)

**Comment by eugenegirard** [comment] 2021-11-11 21:16
Wouldn't touch action tests get ignored for MacOS then?

**Comment by flackr** [comment] 2021-11-11 22:53
Currently they result in failures, but it could be a good goal to update the tests so that lack of touch support on the platform skips the tests.

**Comment by foolip** [comment] 2021-11-22 22:47
Looking at https://wpt.fyi/results/pointerevents?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned, some touch tests are easy to exclude, like any that have "touch" in the test name.

More problematic are any tests that use touch but don't strictly have to. In particular, test using `touchScrollInTarget` would perhaps make sense for wheel-induced scrolling, but I can't find any tests involving "wheel" in pointerevents/. Judging by https://wpt.fyi/results/webdriver/tests/perform_actions/wheel.py?run_id=5675562627497984&run_id=5653017203310592&run_id=5670493089693696 it doesn't work in geckodriver of safaridriver yet.

@flackr would you be able to make a list of tests that would work without touch support, and see if that's still enough to be useful?

**Comment by flackr** [comment] 2021-11-23 19:14
@mustaqahmed Do you think you could help with this?

**Comment by gsnedders** [comment] 2021-11-29 20:37
Looking at https://wpt.fyi/results/pointerevents/idlharness.window.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=%21touch%20%21pen (i.e., excluding both touch and pen) we see much more green than the overall summary. Looking at idlharness:

 * `altitudeAngle`/`azimuthAngle` is unsupported in Gecko/WebKit
 * `getCoalescedEvents`/`getPredictedEvents` is unsupported in WebKit
 * `onpointerrawupdate` is unsupported in Gecko/WebKit

Of the above query, it seems that:

 * 37 subtests fail in all browsers
 * 601 subtests fail in two
 * 230 subtests fail in one
 * 979 subtests pass in all

Given that, I guess the question in part becomes "do we want to exclude any tests/features that [fail in two browsers](https://wpt.fyi/results/pointerevents?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=%21touch%20%21pen%20%20%20count%3A2%28status%3A%21pass%26status%3A%21ok%29)?".

**Comment by foolip** [comment] 2021-12-10 15:44
Per https://github.com/web-platform-tests/interop-2022/issues/39#issuecomment-991001758 we won't include this in Interop 2022, but before closing it we should figure out if there's something here we want to work jointly on in 2022.

@gsnedders can you elaborate on "WPT coverage does not seem representative of site compatibility bugs"? What kinds of site compat issues you tend to see with Pointer Events? Perhaps focusing on those aspects would put this in better shape for Interop 2023.

**Comment by gsnedders** [comment] 2021-12-16 18:08
> @gsnedders can you elaborate on "WPT coverage does not seem representative of site compatibility bugs"? What kinds of site compat issues you tend to see with Pointer Events? Perhaps focusing on those aspects would put this in better shape for Interop 2023.

Looking at [bugs.webkit.org](https://bugs.webkit.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&f0=OP&f1=OP&f10=short_desc&f5=short_desc&f7=content&f8=CP&f9=CP&list_id=7753483&o10=nowordssubstr&o5=substring&o7=matches&query_format=advanced&v10=GTK%20WPE&v5=pointer%20event&v7=%22pointer%20event%22) shows a variety of issues; these are:

 1. Mostly touch related issues, which we don't have test coverage for WebKit on wpt.fyi due to lack of any sort of touch input on macOS, and therefore not in Safari either,
 2. Related to browser features (like drag-to-scroll) which I don't think Pointer Events really covers?

**Comment by karlcow** [comment] 2021-12-17 02:52
so checking webcompat issues related to pointer events. 
https://bugzilla.mozilla.org/buglist.cgi?classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&v1=webcompat&f1=see_also&short_desc=pointer&short_desc_type=allwordssubstr&query_format=advanced&resolution=---&o1=substring&list_id=15938104

* [Firing mouseup/pointerup after contextmenu causes interop issues](https://bugzilla.mozilla.org/show_bug.cgi?id=1563791). This one seems to be partially solved. 
* [Pointer events don't make it to a float in relatively positioned block-in-inline split (with content before & after the float)](https://bugzilla.mozilla.org/show_bug.cgi?id=1487937). This one seems to be working only in Safari Desktop

**Comment by jgraham** [comment] 2021-12-17 09:12
Is this something where a different WebKit port might enable the feature on desktop, and provide a useful proxy for iOS Safari? Or is there a lot of port-specific code?

**Comment by foolip** [comment] 2022-08-18 09:34
Closing this, discussion continues in https://github.com/web-platform-tests/interop-2022-pointer.

**Closed by foolip** 2022-08-18 09:34 UTC
Labels: proposal, requires:test-infra
