### ISSUE TITLE
Accessibility issues with display properties (not including `display: contents`)

### ISSUE THREAD

**Issue by jsnkuhn** [web-platform-tests/interop#512] opened 2023-10-02 19:55 UTC
### Description

This is an incredibly detailed blog post by Adrian Roselli that is following fixes to accessibility issues with CSS display properties (mostly `display: contents;`). The proposal is for Interop2024 to highlight and track the work that is going on here:

https://adrianroselli.com/2022/07/its-mid-2022-and-browsers-mostly-safari-still-break-accessibility-via-display-properties.html

### Specification

https://drafts.csswg.org/css-display/#the-display-properties

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [ ] WebKit

**Comment by cookiecrook** [comment] 2023-10-02 22:41
- https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/60

**Comment by jensimmons** [comment] 2023-10-03 22:28
Tests are needed for this to be a focus area. Does anyone have a pitch for a plan to get them created? How long will it take? Volunteers?

In the past, we've worked on improving test coverage through the end of the previous year — so in this case, we have until mid-December to get the tests written. But we should have a plan by the Oct 12 proposal revision deadline, so the plan is known and can be considered when evaluating whether/not this will be included in Interop 2024.

**Comment by jensimmons** [comment] 2023-10-05 21:52
I'd like to suggest this proposal be defined to focus on `display: contents`. That is definitely an area that needs cross-browser support to reach interoperability. 

<img width="1404" alt="Screenshot 2023-10-05 at 5 46 30 PM" src="https://github.com/web-platform-tests/interop/assets/108474/5ade9b37-fcdb-4c01-bfb0-a30c56d32b2a">

Adrian Roselli did enumerate concerns about `display: grid` and more being applied to table elements in Safari. All of those bugs have been fixed in [Safari 17.0](https://webkit.org/blog/14445/webkit-features-in-safari-17-0/) — so if they were only a problem in WebKit, then there's no work to be done in Interop 2024. 

Also, most of the proposal above ^ is blank. I'd be happy to help fill it out. This is an important area to fix — without accessibility, developers should not be using `display: contents`, and yet they are. 

What do you think @jsnkuhn ? I don't want to fill out the proposal as focused on `display: contents` without your thoughts.

**Comment by cookiecrook** [comment] 2023-10-05 23:42
There are a potential paths I can see being achievable:
- Keep this a Focus Area, but limit the scope to `display: contents` as @jensimmons suggested.
- Keep the broader scope, but change it to a standalone Investigation and/or roll it into #459, the follow-on Accessibility investigation

**Comment by jsnkuhn** [comment] 2023-10-06 13:40
Feeling a bit in over my head here. My purpose in adding this proposal was to highlight that Interop seem like a good place for the issues brought up in the linked article to be tracked. I'm not suggesting that I'm in any way qualified to take on/take over this task. Apologies for forgetting to ping @aardrian in the OP. They are a much better person to be answering the questions asked above.

**Comment by jensimmons** [comment] 2023-10-06 15:42
Let's break this into two issues, so we can discuss each separately. I'll make a focus area proposal for `display: contents`, and we can keep using this issue to discuss the accessibility of all the other values of `display`.

**Comment by jensimmons** [comment] 2023-10-06 16:02
Here's the proposal for `display: contents`. https://github.com/web-platform-tests/interop/issues/568

**Comment by aardrian** [comment] 2023-10-07 21:50
> Apologies for forgetting to ping @aardrian in the OP. They are a much better person to be answering the questions asked above.

As @jensimmons noted, with the latest release of Safari (17) things are much better _for my test cases_ (and excluding `display: contents`). I wrote that post over a year ago, well after the other browsers had mostly sorted their issues (barring a regression), though my updates show the history since. As I have been on holiday until last night, I was only just able to update it with desktop Safari 17 testing notes.

The remaining Safari non-`contents` issue is unlikely to be changed (lists with `display` properties losing semantics) though I defer to Jen or James on that.

**Comment by dholbert** [comment] 2023-10-23 23:42
> Let's break this into two issues, so we can discuss each separately. I'll make a focus area proposal for `display: contents`, and we can keep using this issue to discuss the accessibility of all the other values of `display`.

Could someone summarize what this issue here covers at this point, regarding issues with the other values of `display`?

I might be misunderstanding, but it sounds like @aardrian's comment above might be saying that the non-`contents` issues have been largely fixed ("things are much better for my test cases" / " other browsers had mostly sorted their issues").

(also: I assume the "remaining Safari non-contents issue [...] (lists with display properties losing semantics)" is https://bugs.webkit.org/show_bug.cgi?id=259487 )

**Comment by jensimmons** [comment] 2023-10-25 00:05
> If that's not the case, it'd be great to have a brief synopsis of what parts are still broken that this github-issue is proposing be covered in interop-2024.

Agreed. It feels like at this point, there's no a clear list of what this focus area would cover. 

Also, at the moment, we don't believe https://bugs.webkit.org/show_bug.cgi?id=259487 is a report of a bug, but rather a (handy) report that the comment is out of date. We're looking into it, so aren't 100% sure yet... more later... but meanwhile, it does not look like this is an issue for Interop 2024 — especially since how precisely screenreaders are to handle lists is not standardized. Perhaps it should be, but that's another thing to discuss outside the Interop 2024 Focus Area proposal process.

**Comment by cookiecrook** [comment] 2023-10-27 00:53
> Agreed. It feels like at this point, there's no a clear list of what this focus area would cover.

And typically test cases would be written for specific features before they are proposed as a Focus Area... For example, I hope to work on https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/60 soon for https://github.com/web-platform-tests/interop/issues/568 … I'm hopeful those PRs will show how easy it is to write role and label tests, so if there's an edge case not covered, anyone could add it.

**Comment by dandclark** [comment] 2024-02-01 17:53
Thank you for proposing Accessibility issues with display properties (not including `display: contents`) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We believe this proposal is too broad, and that as such, Interop 2024 is not the right venue to do this focus area.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._

**Closed by dandclark** 2024-02-01 17:53 UTC
Labels: focus-area-proposal

**Comment by jensimmons** [comment] 2024-02-01 17:55
Actually this proposal IS part of Interop 2024. The tests for `display: contents` were written late, but in time to meet the deadline, so they've been folded into the Accessibility focus area. 

They are in the CSS directory in this set of tests: https://wpt.fyi/results/?label=master&label=experimental&aligned&view=interop&q=label%3Ainterop-2024-accessibility

**Comment by jensimmons** [comment] 2024-02-01 17:56
Or, in case you don't want to drill down, the tests are here: https://wpt.fyi/results/css/css-display/accessibility/display-contents-role-and-label.html?label=master&label=experimental&aligned&view=interop&q=label%3Ainterop-2024-accessibility

**Comment by jensimmons** [comment] 2024-02-01 17:57
That's 138 subtests for `display: contents` alone.
