### ISSUE TITLE
Update WebCodecs invalid configuration handling in isConfigSupported, configure tests to match spec.

### ISSUE THREAD

**Issue by dalecurtis** [web-platform-tests/interop#382] opened 2023-07-18 18:00 UTC
### Test List

https://wpt.fyi/results/webcodecs?label=master&label=experimental&aligned&q=webcodecs/video-decoder.https.
https://wpt.fyi/results/webcodecs?label=master&label=experimental&aligned&q=webcodecs/video-encoder-config.https.
https://wpt.fyi/results/webcodecs?label=master&label=experimental&aligned&q=webcodecs/video-encoder.https.

### Rationale

The current test behavior throws/rejects with a `TypeError` for unrecognized codec strings, which is both surprising to developers and an ambiguous interpretation of what the spec says (throw on invalid configs). Since not every UA is going to support every codec string, we shouldn't be throwing exceptions for unrecognized codec strings. Keep in mind unrecognized might just mean a newer variant of a valid codec string than a UA knows about.

Specifically, for `isConfigSupported` this just means not rejecting the promise and instead resolving with `supported` as `false` when a codec string is unrecognized. While for `configure` this changes the type of exception generated from `TypeError` to `NotSupportedError`.

https://github.com/web-platform-tests/wpt/pull/41078 and https://chromium-review.googlesource.com/c/chromium/src/+/4690765 show the precise changes.

@youennf @padenot

**Comment by dalecurtis** [comment] 2023-07-18 21:30
@sandersdan pointed out that @youennf partially fixed this with https://github.com/web-platform-tests/wpt/pull/40691 -- though my proposal does undo part of that change as `scalabilityMode=ABC` is invalid per https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*

**Comment by youennf** [comment] 2023-07-20 10:03
In general, I am in favour of resolving with unsupported instead of rejecting.
I do not think Safari is doing this for codec strings right now but we can adjust.

FWIW, the same invalid codec string would resolve with unsupported=true in one browser that does not understand the codec but would reject in another one that understands the codec. This seems fair to me.

Also, maybe we should add some H264, HEVC and AV1 bad codec strings.

**Comment by gsnedders** [comment] 2023-07-20 14:35
> ambiguous interpretation of what the spec says (throw on invalid configs)

Is there any spec bug tracking clarifying interpretation of the spec?

**Comment by sandersdan** [comment] 2023-07-20 17:42
This is https://github.com/w3c/webcodecs/issues/686.

**Comment by sandersdan** [comment] 2023-07-20 17:47
> FWIW, the same invalid codec string would resolve with unsupported=true in one browser that does not understand the codec but would reject in another one that understands the codec. This seems fair to me.

There isn't a test in this PR that requires this behavior, and the associated change to Chrome is only throwing for empty. It may be that we want to revise the spec text here to not require throwing for 'invalid codec string', since it's not obvious how invalid differs from unrecognized.

**Comment by dalecurtis** [comment] 2023-07-20 19:50
Some invalid codec looking strings are a good idea. I'll add those to the PR. I'll also add some non-normative text around what invalid means in the spec.

**Comment by dalecurtis** [comment] 2023-07-20 20:30
https://github.com/w3c/webcodecs/pull/707 fixes the spec text, I'll add tests for codec strings tomorrow.

@padenot any thoughts?

**Comment by dalecurtis** [comment] 2023-07-21 22:24
The latest version of the tests add a bunch of could bad AV1, VP9, H264, HEVC, Opus, and AAC codec strings.

**Comment by padenot** [comment] 2023-07-27 12:03
Sorry about the delay here, this can be merged without problem indeed.

**Comment by dalecurtis** [comment] 2023-07-27 16:01
Thanks @padenot! Looks like wpt merge is blocked by some unrelated flake around VideoFrames from SVG on Firefox Nightly: https://github.com/web-platform-tests/wpt/runs/15381657289 -- can you take a look?

**Comment by padenot** [comment] 2023-07-27 16:25
The patch for this is at https://bugzilla.mozilla.org/show_bug.cgi?id=1839169, I think I just need to rebase + land it.

Can we merge this anyway?

**Comment by dalecurtis** [comment] 2023-07-27 16:39
Maybe one of the WPT infra folks can. I don't see any self-service button to do so though.

No rush either way, thanks for investigating Paul!

**Closed** 2023-07-27 19:04 UTC
Labels: test-change-proposal

**Comment by dalecurtis** [comment] 2023-08-18 00:29
https://github.com/web-platform-tests/wpt/pull/41421 ended up changing the tests here again, but didn't go through the interop process. That change is correct, but didn't update anything but video decoder. I'll put up a PR to fix that tomorrow, Chrome side change is WIP here: https://chromium-review.googlesource.com/c/chromium/src/+/4786867

**Comment by dalecurtis** [comment] 2023-08-21 16:58
https://github.com/web-platform-tests/wpt/pull/41540 applies the changes Firefox made to all tests: Per spec `NotSupportedError` is delivered to the error callback and not directly to the `configure` call.

@youennf FYI.
@padenot it seems to currently crash Firefox: https://github.com/web-platform-tests/wpt/runs/16026849222 -- not sure what's going on there.

**Comment by youennf** [comment] 2023-09-05 17:41
Can we proceed and merge [web-platform-tests/wpt#41540](https://github.com/web-platform-tests/wpt/pull/41540)?
Looking at the PR itself, it assumes flush would reject with InvalidStateError, I would expect NotSupportedError in that case.

**Comment by dalecurtis** [comment] 2023-09-05 18:20
It's pending resolution of https://github.com/w3c/webcodecs/issues/711 -- can you weigh in there @youennf ?

**Comment by dalecurtis** [comment] 2023-09-05 18:32
If the `flush()` happens after the failed configure, it's supposed to be `InvalidStateError`; if the `flush()` is pending when the `configure()` fails then it would be `NotSupportedError`.
https://w3c.github.io/webcodecs/#dom-videodecoder-flush
https://w3c.github.io/webcodecs/#dom-videodecoder-configure

`configure()` results in processing the control message queue, so I think either is possible depending on how the UA determines that `configure()` is unsupported. E.g., if UA must make an asynchronous determination that the codec is not supported, it's likely to end up with `NotSupportedError`, if UA determines codec isn't supported immediately it can reject during the control message processing before `flush()` is called.

I'm not sure it's possible to guarantee one state or the other without some big spec changes. WDYT?

**Comment by youennf** [comment] 2023-09-05 19:00
> If the `flush()` happens after the failed configure, it's supposed to be `InvalidStateError`

The only `InvalidStateError` case I see for flush is if the state is not configured.
This can happen if configure would close the decoder/encoder synchronously, before the flush() call.

The issue is that configure might fail asynchronously in some cases and synchronously in some other cases.
It seems best if this is not made observable to JS.
I would therefore vote for going with `NotSupportedError` for any flush() calls that happens before the error event callback is executed, and then `InvalidStateError`.

The spec is not close to that model as currently written but maybe we can still update it somehow.
We could try to do something like:
- block the queue before we check the configuration support and keep it blocked until the error callback is executed.
- queue a task to change the state to "closed" and synchronously call the error callback, like we usually do for any state change event (queue a task, change the state and synchronously fire the event).

**Comment by dalecurtis** [comment] 2023-09-05 19:27
Queuing a task to run the close algorithm and synchronously execute the error callback sgtm -- though most state changes aren't posted FWIW, only encoding/decoding errors. I think that seems safe, but @sandersdan in case there's something I'm forgetting about the processing model.

**Comment by sandersdan** [comment] 2023-09-07 18:18
This is one of the key reasons we went with callbacks (so that we can order state changes relative to those calls executing). Ideally there would be no difference between calling `flush()` before or after the implementation discovers an error (until the callback actually executes).

**Comment by youennf** [comment] 2023-09-22 16:03
I see that https://github.com/web-platform-tests/wpt/commit/fda8482a038ad6a0b55f324d4cb11b99a68dded2 video-decoder.https.any.js expects flush() to reject with InvalidStateError when configure() is called with future H264/HEVC codec strings.

This means that the error callback is expected to be called synchronously which might not be true for all implementations, including WebKit.
Either we update the test to account for this or we change the spec to queue a task to change the state of the decoder to closed. I would prefer the latter, it seems strange to do:
- set decoder state to closed
- queue a task to run the error callback.

**Comment by dalecurtis** [comment] 2023-09-22 19:06
Queuing a task sgtm. Sorry I forgot about this aspect of our discussion. I'll poke at this today and update the test.

**Comment by dalecurtis** [comment] 2023-09-22 20:37
https://github.com/web-platform-tests/wpt/pull/42127
