### ISSUE TITLE
[offscreencanvas] Update the OS/2 table in the CanvasTest font to v.4 and set USE_TYPO_METRICS flag

### ISSUE THREAD

**Issue by jfkthame** [web-platform-tests/interop#386] opened 2023-07-26 16:49 UTC
### Test List

https://wpt.fyi/results/html/canvas/offscreen/text?label=master&label=experimental&aligned&q=fontboundingbox

This potentially affects any tests that use the CanvasTest.ttf font; specifically, the expectations of the fontBoundingBox tests will change, but depending on implementation details, browsers might see behavior changes on other tests that use the font.

### Rationale

The CanvasTest.ttf font, used in tests for the TextMetrics attributes such as fontBoundingBoxAscent/Descent, has only a version 1 'OS/2' table, which is a long-obsolete version. We should update it to support a more modern version of the OpenType spec.

This is significant to the metrics tests because fonts contain multiple "ascent" and "descent" metrics, and legacy behaviors vary across platforms and applications as to how these are used.

The [spec for fontBoundingBoxAscent](https://html.spec.whatwg.org/multipage/canvas.html#dom-textmetrics-fontboundingboxascent), for example, refers to "the [ascent metric](https://drafts.csswg.org/css-inline/#ascent-metric) of the [first available font](https://drafts.csswg.org/css-fonts/#first-available-font)". But what exactly is "the ascent metric"? Well, it's linked to the [CSS Inline spec](https://drafts.csswg.org/css-inline/#ascent-metric), but that offers only a recommendation (and not a requirement) to use the `sTypoAscender` value from the 'OS/2' table.

Currently, though, the expectation of the fontBoundingBoxAscent tests appears to be based on the `usWinAscent` field, or the `ascent` of the 'hhea' table (which in this font is the same, though there's no guarantee of that in general). But there's no clear spec anywhere (that I can tell) to justify this.

Recognizing the problem of multiple, conflicting versions of these metrics, more recent versions of the OpenType spec introduced a flag [`USE_TYPO_METRICS`](https://learn.microsoft.com/en-gb/typography/opentype/spec/os2#fsselection), which font designers can set to "strongly recommend" that applications respect the `sTypo*` metrics (rather than alternatives such as `usWin*` or the 'head' table values). This flag was defined in version 4 of the 'OS/2' table, and the spec notes that "vendors are encouraged to use a version 4 or later OS/2 table and to have bit 7 [the USE_TYPO_METRICS flag] set".

So, to better conform with current OpenType recommendations and to provide a more solid basis for interoperable behavior, I propose that we should set this flag in the CanvasTest font (updating the 'OS/2' table to v.4), and adjust the expectations of the fontBoundingBoxAscent/Descent tests to correspond to these "preferred" metrics. This will also make the test font more representative of font resources being created and used in "real-world" content today.

**Comment by jfkthame** [comment] 2023-07-26 16:57
Note that in Gecko bug https://bugzilla.mozilla.org/show_bug.cgi?id=1841692 I have a patch that will update the CanvasTest.ttf font as proposed here. If there are concerns about this, please let me know and we can consider alternative approaches.

**Comment by chrishtr** [comment] 2023-08-18 22:32
@drott can you review this for Chromium?

**Comment by drott** [comment] 2023-08-22 17:37
After discussion with @kojiishi , we're still not sure what CoreText gives us back, and whether we really always read `sTypo(Asc|Desc)ender`. 
According to this recent article https://developer.chrome.com/blog/font-fallbacks/#understanding-font-tables where @khempenius went through this, Chrome on Mac may rely on `hhea` and we'd suggest for the updated font to have these metrics still set so that they match the updated `OS/2` table.

Further context:
* https://github.com/w3c/csswg-drafts/issues/4792
* https://github.com/w3c/csswg-drafts/issues/2228#issuecomment-631657902

**Comment by drott** [comment] 2023-08-22 17:46
> Note that in Gecko bug https://bugzilla.mozilla.org/show_bug.cgi?id=1841692 I have a patch that will update the CanvasTest.ttf font as proposed here.

I put that in https://gist.github.com/drott/220ec0917092572b6258e5267d757b77 as a ttx comparison, and it looks like you're not suggesting to change `hhea`, but the `fsSelection` bit update and the version change are in there.

**Comment by drott** [comment] 2023-08-29 07:45
Compare related issue #5380 for a similar discussion on what to do when a metric is not available.

**Comment by gsnedders** [comment] 2023-08-31 21:15
> After discussion with @kojiishi , we're still not sure what CoreText gives us back, and whether we really always read `sTypo(Asc|Desc)ender` for Mac.

According to the CoreText team: "CoreText observes `USE_TYPO_METRICS` when there is a `STAT` table".

As such, in principle, we're fine with the change.

FWIW, I'd rather we triggered full WPT runs on the WPT infra to check that this doesn't cause extra regressions.

**Comment by nt1m** [comment] 2023-09-21 11:54
WebKit is making a similar change in https://github.com/WebKit/WebKit/pull/17474 , so we support it.

**Comment by nt1m** [comment] 2023-09-22 00:57
Will close this bug as I don't think there is any more action to do here.

**Closed by nt1m** 2023-09-22 00:57 UTC
Labels: test-change-proposal, focus area: Offscreen Canvas

**Comment by gsnedders** [comment] 2023-09-22 10:02
> WebKit is making a similar change in [WebKit/WebKit#17474](https://github.com/WebKit/WebKit/pull/17474) , so we support it.

And exported in https://github.com/web-platform-tests/wpt/pull/42109.
