### ISSUE TITLE
Compat 2021 carryover

### ISSUE THREAD

**Issue by chrishtr** [web-platform-tests/interop#2] opened 2021-10-29 18:22 UTC
[Compat2021](https://wpt.fyi/compat2021) is the predecessor to Interop2022. It [defined 5 key areas](https://web.dev/compat2021) where interop was not good enough between browsers, as backed up by strong evidence from developer surveys. All five areas are fully supported features from all browser engines.

Over the course of 2021, there has been [excellent progress](https://web.dev/compat2021-midyear/) in the score for all three browser rendering engines. All three are above 90% at this point for their tip-of-tree implementations, whereas at the beginning of the year none were. (Note: the Safari score on the current website is not accurate, due to a technical complication; the actual score is about 92).

I would like to propose that the Compat2021 areas be included as part of the Interop2022 score. This will reinforce that we want interop to continue improving and be sustained for "last year's" metric, not just the new hotness.

**Comment by fantasai** [comment] 2021-11-03 23:42
Strong +1. In particular, I think we still have work to do on Grid and Flexbox layout, and I wouldn't be surprised if there are some bugs and issues around aspect-ratio or postion:sticky, so it would be good to keep them at a high priority.

**Comment by jgraham** [comment] 2021-11-11 11:46
I think there's some overlap with #9 in that they are both looking for ways to include ongoing improvements to existing features rather than just focusing on implementing new functionality. I fully agree that this kind of priority is a good idea. However I don't think we should blindly roll over the existing tests/areas, for two reasons:
* For Compat 2021 in particular there was less explicit buy-in on the focus areas. I think going forward everything should be held to the same standard. Obviously this wouldn't be such a concern in future iterations.
* It makes sense to reassess the set of tests + etc. to ensure that any remaining failure are things that we think are likely to affect authors, and to ensure that we aren't missing any important cases that weren't included in Compat 2021 due to lack of coverage (i.e. where new tests have been written since the original list was picked).

**Comment by foolip** [comment] 2021-11-11 15:14
Vetting the set of tests for Compat 2021 would be a good idea I think.

I like the model of including all tests in the latest metric, since it means there's just one metric at a time to focus on, but a downside is that over time, the new tests would account for less and less of the overall score. One could mitigate this by weighting new tests to be at least 50%, but that would also make the metric a bit harder to understand.

**Comment by foolip** [comment] 2021-11-18 17:36
Added label to mean that we should revisit the tests, not that we don't know what they are.

**Comment by foolip** [comment] 2021-11-22 21:21
It will soon be easier to review the list of tests for Compat 2021. https://github.com/web-platform-tests/wpt-metadata/pull/2196 is the first PR labeling some tests, using "interop-2021" as the label, and once that works I'll label all of them. Then it will be easy to filter out just the tests that are failing in some browser for review.

**Comment by foolip** [comment] 2021-11-24 14:19
The labeling support has landed and I've added the `interop-2021` labels. Here are all the tests from Compat 2021, and another view filtered to failing (non-passing) tests:
- [label:interop-2021](https://staging.wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021)
- [label:interop-2021 (status:!pass&status:!ok)](https://staging.wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021%20%28status%3A%21pass%26status%3A%21ok%29)

**Comment by jensimmons** [comment] 2021-11-29 16:34
Digging into the tests, it’s interesting to see that Compat 2021 included both:
- the new CSS property, `aspect-ratio`
- the new sizing calculations based on using width & height HTML attributes to calculate an aspect ratio to use in first paint

Those are two very different things. Only the first one was written up in the publicity about this project. But there are tests for both. 

Interesting.

**Comment by gsnedders** [comment] 2021-11-29 17:12
Also would be interesting to review would be what tests were excluded (modulo obvious cases, like subgrid and masonry for grid).

That said, there's probably an argument that if we want to do it as carry-over (in part to avoid massively regression scores of existing browsers), then we should just keep the same sets.

**Comment by foolip** [comment] 2021-11-30 08:46
There may be

**Comment by foolip** [comment] 2021-11-30 08:53
> Also would be interesting to review would be what tests were excluded (modulo obvious cases, like subgrid and masonry for grid).

Commented out lines and comments in these files might help:
https://raw.githubusercontent.com/Ecosystem-Infra/wpt-results-analysis/main/compat-2021/aspect-ratio-tests.txt
https://raw.githubusercontent.com/Ecosystem-Infra/wpt-results-analysis/main/compat-2021/css-flexbox-tests.txt
https://raw.githubusercontent.com/Ecosystem-Infra/wpt-results-analysis/main/compat-2021/css-grid-tests.txt
https://raw.githubusercontent.com/Ecosystem-Infra/wpt-results-analysis/main/compat-2021/css-transforms-tests.txt
https://raw.githubusercontent.com/Ecosystem-Infra/wpt-results-analysis/main/compat-2021/position-sticky-tests.txt

Pulling out the linked docs/spreadsheets:
- [flex tests chromium.org](https://docs.google.com/spreadsheets/d/11UHJJvy6GZDuaaGwNHTeNGWXZb5NtCb_G3hgG7cdUu4/edit)
- [Grid WPT notes](https://docs.google.com/document/d/1kK3bnZdM-y49gbKPD5RUBz_PsHjvGtQ_8qrDcSu4DVg/edit)
- [sticky tests](https://docs.google.com/spreadsheets/d/1WtTgV1VQB0XLFMpTCeFbTlXRoygqsPyap6MkFtPXCas/edit) (a copy, since the original doesn't have the right sharing settings)

**Comment by foolip** [comment] 2021-11-30 09:27
@jensimmons `aspect-ratio` and the new behavior of `width` and `height` attributes are indeed not the same thing, but the latter is [defined in terms of the former](https://html.spec.whatwg.org/#map-to-the-aspect-ratio-property) and [tested](https://github.com/web-platform-tests/wpt/blob/3f103ef2cd46ee0ef2c92e14ef9b7753353514a4/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/resources/aspect-ratio.js#L10-L11) using it as well. Having both tools available and interoperable seemed like a good idea, so we included the attributes under the `aspect-ratio` banner.

We can of course revisit this as part of this issue, if some of the tests aren't good.

**Comment by foolip** [comment] 2021-11-30 09:29
In https://github.com/Ecosystem-Infra/wpt-results-analysis/pull/66 @dholbert found an excluded a Houdini-dependent transforms test. I've merged the PR to retroactively exclude it, but we should consider including this test instead:
https://wpt.fyi/results/css/css-transforms/animation/transform-interpolation-inline-value.html

**Comment by foolip** [comment] 2021-11-30 10:32
Thanks to that I also noticed there are some [tentative](https://web-platform-tests.org/writing-tests/file-names.html?highlight=tentative) tests included in Compat 2021. Quick analysis:

<table>
<tr>
  <th>test
  <th>results
<tr>
  <td><a href="https://wpt.fyi/results/css/css-flexbox/table-as-item-min-content-height-1.tentative.html?run_id=5648693177876480&run_id=5717400826675200&run_id=5638396849422336">/css/css-flexbox/table-as-item-min-content-height-1.tentative.html</a>
  <td>all pass
<tr>
  <td><a href="https://wpt.fyi/results/css/css-flexbox/table-as-item-min-content-height-2.tentative.html?run_id=5648693177876480&run_id=5717400826675200&run_id=5638396849422336">/css/css-flexbox/table-as-item-min-content-height-2.tentative.html</a>
  <td>all pass
<tr>
  <td><a href="https://wpt.fyi/results/css/css-grid/alignment/replaced-alignment-with-aspect-ratio-003.tentative.html?run_id=5648693177876480&run_id=5717400826675200&run_id=5638396849422336">/css/css-grid/alignment/replaced-alignment-with-aspect-ratio-003.tentative.html</a>
  <td>all pass
<tr>
  <td><a href="https://wpt.fyi/results/css/css-position/sticky/position-sticky-large-top-2.tentative.html?run_id=5648693177876480&run_id=5717400826675200&run_id=5638396849422336">/css/css-position/sticky/position-sticky-large-top-2.tentative.html</a>
  <td>all pass
<tr>
  <td><a href="https://wpt.fyi/results/css/css-transforms/backface-visibility-hidden-002.tentative.html?run_id=5648693177876480&run_id=5717400826675200&run_id=5638396849422336">/css/css-transforms/backface-visibility-hidden-002.tentative.html</a>
  <td>Safari fails
<tr>
  <td><a href="https://wpt.fyi/results/css/css-transforms/backface-visibility-hidden-003.tentative.html?run_id=5648693177876480&run_id=5717400826675200&run_id=5638396849422336">/css/css-transforms/backface-visibility-hidden-003.tentative.html</a>
  <td>Safari fails
<tr>
  <td><a href="https://wpt.fyi/results/css/css-transforms/backface-visibility-hidden-004.tentative.html?run_id=5648693177876480&run_id=5717400826675200&run_id=5638396849422336">/css/css-transforms/backface-visibility-hidden-004.tentative.html</a>
  <td>Chrome+Firefox fail
<tr>
  <td><a href="https://wpt.fyi/results/css/css-transforms/backface-visibility-hidden-005.tentative.html?run_id=5648693177876480&run_id=5717400826675200&run_id=5638396849422336">/css/css-transforms/backface-visibility-hidden-005.tentative.html</a>
  <td>Chrome+Firefox fail
<tr>
  <td><a href="https://wpt.fyi/results/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/img-aspect-ratio-lazy.tentative.html?run_id=5648693177876480&run_id=5717400826675200&run_id=5638396849422336">/html/rendering/.../img-aspect-ratio-lazy.tentative.html</a>
  <td>all pass
</table>

Whether passing or failing, I think next steps for these tests should be to look into why they're tentative, and if the they can be renamed yet. In cases where they still have to be tentative, we should remove them from the Compat 2021 set.

I've prepared https://github.com/Ecosystem-Infra/wpt-results-analysis/pull/67 + https://github.com/web-platform-tests/wpt-metadata/pull/2218 to drop them, but want to look closer first.

**Comment by foolip** [comment] 2021-11-30 11:04
The Flexbox tentative tests came from https://chromium-review.googlesource.com/c/chromium/src/+/2810520 with this comment:
> There is no spec requiring this in the block direction, even though Firefox and legacy Blink both do it, and there is a spec requirement for the inline direction. So the tests are marked tentative.

The Grid test

@davidsgrogan do you know if there's an open spec issue for this? I've searched https://github.com/w3c/csswg-drafts/issues but am unsure if any are related.

----

The Grid test came from https://chromium-review.googlesource.com/c/chromium/src/+/2523743 and links to https://github.com/w3c/csswg-drafts/issues/5713. That's resolved now, so probably that test can be renamed. @bfgeek can you confirm?

----

The `position: sticky` test came from https://chromium-review.googlesource.com/c/chromium/src/+/2528572 and links to https://github.com/w3c/csswg-drafts/issues/2794 which remains open. I've asked a naive question on the issue.

----

The transforms tests came from https://chromium-review.googlesource.com/c/chromium/src/+/2197895, but I can't find any links or comments explaining why they're tentative. @chrishtr can you help look into these, is there a spec issue for this?

---

Finally, img-aspect-ratio-lazy.tentative.html came from https://phabricator.services.mozilla.com/D66257 but I can't see anything explaining why it's tentative. @emilio can you help look into this one?

**Comment by gsnedders** [comment] 2021-11-30 14:01
> * [flex tests chromium.org](https://docs.google.com/spreadsheets/d/11UHJJvy6GZDuaaGwNHTeNGWXZb5NtCb_G3hgG7cdUu4/edit)

I don't have access to that.

**Comment by emilio** [comment] 2021-11-30 15:03
> Finally, img-aspect-ratio-lazy.tentative.html came from https://phabricator.services.mozilla.com/D66257 but I can't see anything explaining why it's tentative. @emilio can you help look into this one?

I think I made it tentative because I didn't find the relevant spec text at the time. I guess the "the user agent does not expect this to change" bits in https://html.spec.whatwg.org/multipage/rendering.html#images-3 sorta cover this case, but the spec doesn't say what happens when none of these conditions happen (presumably you go to the replaced element rendering).

But yeah the test should probably not be tentative, and we should fix the spec to be clear.

**Comment by foolip** [comment] 2021-12-01 08:55
Two more tests I think we should reconsider are print reftests, which Edge and Safari don't run at all:
https://wpt.fyi/results/css/css-flexbox?q=print&run_id=5763010778890240&run_id=5717707447074816&run_id=5674576043311104&run_id=5652492663652352

@gsnedders is print reftest support for Safari something you think might materialize in 2022? If not, I think we should drop these tests, WDYT?

**Comment by foolip** [comment] 2021-12-01 09:09
> > Finally, img-aspect-ratio-lazy.tentative.html came from https://phabricator.services.mozilla.com/D66257 but I can't see anything explaining why it's tentative. @emilio can you help look into this one?
> 
> I think I made it tentative because I didn't find the relevant spec text at the time. I guess the "the user agent does not expect this to change" bits in https://html.spec.whatwg.org/multipage/rendering.html#images-3 sorta cover this case, but the spec doesn't say what happens when none of these conditions happen (presumably you go to the replaced element rendering).
> 
> But yeah the test should probably not be tentative, and we should fix the spec to be clear.

Thanks for looking into this, @emilio! I've sent https://github.com/web-platform-tests/wpt/pull/31805 to rename the test and requested your review.

**Comment by gsnedders** [comment] 2021-12-01 18:06
> @gsnedders is print reftest support for Safari something you think might materialize in 2022? If not, I think we should drop these tests, WDYT?

Apple does not comment on future products or releases.

**Comment by foolip** [comment] 2021-12-01 21:04
@gsnedders 😄

I take that to mean it requires some changes to Safari or safaridriver, I wasn't sure if it might be a matter of wptrunner bits only.

So, if anyone, for any reason or no reason, wants to drop print reftests from the test list, I think we should do that.

**Comment by foolip** [comment] 2021-12-02 16:08
https://github.com/Ecosystem-Infra/wpt-results-analysis/pull/69 is another case for our consideration, where @stephenmcgruer discovered that two tests pass in Chrome Dev only because of `--experimental-web-platform-features` and that behavior isn't on its way to stable. I'd default to dropping those tests, but it would be good to get the input of other browser vendors on the behavior in question.

**Comment by gsnedders** [comment] 2021-12-14 14:48
We should probably at least triage https://wpt.fyi/results/?label=master&label=stable&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021%20count%3A3%28status%3A%21pass%26status%3A%21ok%29 (i.e., tests that fail in stable releases of all three major engines).

**Comment by foolip** [comment] 2022-01-10 14:49
These are all labeled now:


- [`interop-2021-aspect-ratio`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-aspect-ratio)
- [`interop-2021-flexbox`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-flexbox)
- [`interop-2021-grid`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-grid)
- [`interop-2021-position-sticky`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-position-sticky)
- [`interop-2021-transforms`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-transforms)

[Query for all of these labels together](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-aspect-ratio%20or%20label%3Ainterop-2021-flexbox%20or%20label%3Ainterop-2021-grid%20or%20label%3Ainterop-2021-position-sticky%20or%20label%3Ainterop-2021-transforms)

**Comment by foolip** [comment] 2022-01-20 10:20
Given no pushback on https://github.com/web-platform-tests/interop-2022/issues/2#issuecomment-984053009, I have dropped the print reftests in https://github.com/Ecosystem-Infra/wpt-results-analysis/commit/f805a0eaeab7568ffc53d2df9b363ebc5b76bf68 + https://github.com/web-platform-tests/wpt-metadata/pull/2403.

**Comment by foolip** [comment] 2022-01-20 10:30
A live list of remaining tentative tests is here:
https://wpt.fyi/results/css?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=tentative%20%28label%3Ainterop-2021-aspect-ratio%20or%20label%3Ainterop-2021-flexbox%20or%20label%3Ainterop-2021-grid%20or%20label%3Ainterop-2021-position-sticky%20or%20label%3Ainterop-2021-transforms%29

One the transforms tests have any failures. @chrishtr you added these tests in https://github.com/web-platform-tests/wpt/pull/23865, can you help check if they should still be tentative?

**Comment by foolip** [comment] 2022-01-20 15:09
One Grid test from Interop 2021 came up in https://github.com/web-platform-tests/interop-2022/issues/48:

> [/css/css-grid/grid-definition/grid-limits-001.html](https://wpt.fyi/results/css/css-grid/grid-definition/grid-limits-001.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Safari. I've tried running it locally and it just shows a white page, but no console errors.

I would guess the test is OK since it passes in Chrome and Firefox, but this might be worth looking into for someone on the WebKit team, just in case it's a bad test that needs fixing.

**Closed** 2022-08-18 09:18 UTC
Labels: proposal, requires:tests, accepted
